# Generated by Django 4.2.2 on 2023-06-29 11:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters')),
                ('ru_title', models.CharField(max_length=255)),
                ('orig_title', models.CharField(max_length=255)),
                ('released_year', models.CharField(blank=True, max_length=15, null=True)),
                ('rating_imdb', models.FloatField(max_length=5)),
                ('runtime', models.IntegerField()),
                ('iframe_src', models.CharField(max_length=255, unique=True)),
                ('imdb_id', models.CharField(max_length=25)),
                ('kinopoisk_id', models.CharField(max_length=25)),
                ('view_count', models.IntegerField(default=0)),
                ('favourites_count', models.IntegerField(default=0)),
                ('slug_link', autoslug.fields.AutoSlugField(editable=False, populate_from='ru_title', unique_with=['ru_title'])),
            ],
            options={
                'unique_together': {('ru_title', 'orig_title')},
            },
        ),
    ]
